/* 
Code generated by Fahmin GULIYEV

Write a program which takes as argument the name of a directory and then:
1. displays the system time, using seconds and micro-seconds (system call:
gettimeofday) ;
2. runs (using one of the exec primitives) the ls command with the option -l on
the directory provided as parameter;
3. display the time (as before) and the time the command ls took to run
*/
#include<stdio.h>
#include<sys/time.h>
#include<unistd.h> 
#include<stdlib.h>
#include<wait.h>
#include<sys/types.h>
#include<fcntl.h>


void main(int argc, char const *argv[]){
    // As given in the statement we have process, so I prefer use forking. 
    if(argc != 2){
            perror("Not valid arguments\n");
            exit(1);
        }
        int status;
        int  pid = fork();
        if (pid<0){	
            perror("Fork failed");
            exit(2);
        }
        if (pid==0){
            execlp("ls", "ls", "-l",argv[1],  NULL);
            exit(3);
        }
        else{
            struct timeval timeBeginning,timeEnding;
            gettimeofday(&timeBeginning, 0);
            printf("Beginning time:  %ld(seconds)\t%ld(mseconds)\n-----------------------------------------\n",timeBeginning.tv_sec,timeBeginning.tv_usec );
            printf("Procedure is going\n");
            wait(&status);
            printf("Procedure has been ended after status waiting\n-----------------------------------------\n");
            gettimeofday(&timeEnding, 0);
            printf("\nEnding Time:  %ld(seconds)\t%ld(mseconds)\n-----------------------------------------\n",timeEnding.tv_sec,timeEnding.tv_usec );
            long int  taken = (timeEnding.tv_sec-timeBeginning.tv_sec)*1000000 + (timeEnding.tv_usec-timeBeginning.tv_usec);
            printf("The procedure took %ld (microseconds)\n-----------------------------------------\n",taken );
        }
}
