/*
Code generated by Fahmin GULIYEV

Write a program which displays the type of the requested file (directory, ordinary
file, . . . ), as well as its permissions (read, write, execute, in the same way as the
command ls does using option-l) and last modified date. The name of the file
should be given as an argument in Linux shell. 
*/

#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <sys/stat.h>
#include <dirent.h>
#include<wait.h>
#include<fcntl.h>


int fileOrDir(DIR *cand){
    // returns 1 if the path is directory 0 is folder
    if (cand)
        return 1;
    return 0;
}





void displayPermissions(char *path){
    struct stat _stat;
    if (stat(path, &_stat) == 0){
        printf("File permission is:\t");
        printf((S_ISDIR(_stat.st_mode)) ? "d" : "-");
        printf((_stat.st_mode & S_IRUSR) ? "r" : "-");
        printf((_stat.st_mode & S_IWUSR) ? "w" : "-");
        printf((_stat.st_mode & S_IXUSR) ? "x" : "-");
        printf((_stat.st_mode & S_IRGRP) ? "r" : "-");
        printf((_stat.st_mode & S_IWGRP) ? "w" : "-");
        printf((_stat.st_mode & S_IXGRP) ? "x" : "-");
        printf((_stat.st_mode & S_IROTH) ? "r" : "-");
        printf((_stat.st_mode & S_IWOTH) ? "w" : "-");
        printf((_stat.st_mode & S_IXOTH) ? "x" : "-");
    }
    else    fprintf(stderr, "File could not be read\n");
}





void displayLastModData(char *path){
    struct stat _stat;
    if (stat(path, &_stat) == 0){
        struct tm dateTime;
        time_t _time = time(NULL);
        localtime_r(&_time, &dateTime);
        long int offset = dateTime.tm_gmtoff;
        _stat.st_mtime += offset;
        dateTime = *(gmtime(&_stat.st_mtime));
        printf("\tLast Modified Date:\t %02d/%02d/%d %d:%02d:%02d\n", dateTime.tm_mday, dateTime.tm_mon + 1, dateTime.tm_year + 1900,
               dateTime.tm_hour, dateTime.tm_min, dateTime.tm_sec);
    }
    else
        fprintf(stderr, "File could not be read\n");
}




void main(int argc, char *argv[]){
    if (argc != 2){
        fprintf(stderr, "You did not give the argument correctly\n");
        exit(1);
    }
    printf("Information the entry %s\n", argv[1]);
    DIR *cand;
    struct dirent *dir;
    cand = opendir(argv[1]);
    if (fileOrDir(cand)){
        printf("'%s':Entry is  Directory \n\n", argv[1]);
        for (int i = 1; (dir = readdir(cand)) != NULL; i++){
            printf(" Folder number : %d is    '%s': \t", i, dir->d_name);
            displayPermissions(dir->d_name);
            displayLastModData(dir->d_name);
            printf("-------------------------\n\n");
        }
        closedir(cand);
    }
    else{
        printf("'%s':Ordinary File \n\n", argv[1]);
        displayPermissions(argv[1]);
        displayLastModData(argv[1]);
    }
}
